name: {{name.snakeCase()}}
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.0.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0

  cupertino_icons: ^1.0.2
  flutter_triple: ^2.0.1

dev_dependencies:
  mockito: ^5.3.2
  flutter_lints: ^2.0.0
  triple_test: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.3.0
  modular_test: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/logo/
